"""SQLite for the human preference labels (FEATURE_011 §9).

This file holds the only thing in the project that cannot be regenerated by
re-running a script. Every other artefact under `results/` is a function of the
code and a seed; 300 preference judgements are ~100 minutes of somebody's
attention. That asymmetry is why this module is deliberately strict: it would
rather raise than accept a row that quietly corrupts the set.

Two constraints live in the schema itself rather than only in Python, because
Diya's labelling page (PROJECT_BRIEF §9) writes to this same file and will not
be going through this class:

  CHECK (choice IN ('left','right','tie'))   a fourth value is a bug upstream
  UNIQUE (pair_id, labeller_id)              one opinion per person per pair

The second is what makes Cohen's kappa meaningful. Kappa compares two
*independent* judgements; without the constraint the double-labelled set could
contain one person agreeing with themselves and nothing would notice.

CONSTRAINTS #23: the columns are the whole permitted vocabulary — an opaque
labeller id, a choice, a timestamp, and how long it took. There is deliberately
nowhere to record a name, an employer or a client.

The database file is gitignored twice over (`results/*` and `*.db`) and named
in CONSTRAINTS #19. Back it up outside the repo and keep `export_csv` output
beside it.
"""

import csv
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

# The three answers a labeller can give. 'tie' is PROJECT_BRIEF §6.2's
# "can't tell" — a real answer, not a missing one, and the reward model must
# treat it as such in Phase 5b.
CHOICES: tuple[str, ...] = ("left", "right", "tie")

_SCHEMA = """
CREATE TABLE IF NOT EXISTS labels (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    pair_id       TEXT    NOT NULL,
    labeller_id   TEXT    NOT NULL,
    choice        TEXT    NOT NULL CHECK (choice IN ('left', 'right', 'tie')),
    created_at    TEXT    NOT NULL,
    seconds_taken REAL,
    UNIQUE (pair_id, labeller_id)
);
"""

_COLUMNS = ("id", "pair_id", "labeller_id", "choice", "created_at", "seconds_taken")


class LabelStoreError(Exception):
    """Base for every refusal this module makes."""


class InvalidChoiceError(LabelStoreError):
    """A choice outside CHOICES. Raised before touching the database."""


class DuplicateLabelError(LabelStoreError):
    """This labeller has already answered this pair.

    Typed rather than a bare IntegrityError so a caller — the UI, a CLI, an
    import script — can tell 'already answered' apart from 'the disk is full'
    and show the labeller something useful.
    """


def _utc_now() -> str:
    """ISO-8601 in UTC with a trailing Z. Labellers may be in two timezones."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


class LabelStore:
    """A connection to the label database.

    Usable as a context manager, which is the form to prefer — an unclosed
    SQLite handle on Windows keeps a lock on the file and the next labelling
    session fails for a reason that looks nothing like its cause.
    """

    def __init__(self, path: str | Path) -> None:
        self.path = Path(path)
        # results/rlhf/ does not exist on a fresh clone; results/ is gitignored.
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self._conn = sqlite3.connect(self.path)
        self._conn.row_factory = sqlite3.Row
        self._conn.execute("PRAGMA foreign_keys = ON")
        self._conn.executescript(_SCHEMA)
        self._conn.commit()

    # -- lifecycle ---------------------------------------------------------

    def __enter__(self) -> "LabelStore":
        return self

    def __exit__(self, *exc_info) -> None:
        self.close()

    def close(self) -> None:
        self._conn.close()

    # -- writing -----------------------------------------------------------

    def add_label(
        self,
        pair_id: str,
        labeller_id: str,
        choice: str,
        seconds_taken: float | None = None,
        created_at: str | None = None,
    ) -> int:
        """Record one judgement. Returns the new row id.

        `seconds_taken` stays None when the caller did not measure it. A
        defaulted 0.0 would read as an instant decision and would silently
        skew any later analysis of how long people spent thinking.

        `created_at` is injectable so tests are reproducible; production
        callers leave it out and get UTC now.
        """
        if choice not in CHOICES:
            raise InvalidChoiceError(
                f"choice must be one of {CHOICES}, got {choice!r}"
            )

        try:
            cursor = self._conn.execute(
                "INSERT INTO labels (pair_id, labeller_id, choice, created_at, "
                "seconds_taken) VALUES (?, ?, ?, ?, ?)",
                (pair_id, labeller_id, choice, created_at or _utc_now(), seconds_taken),
            )
        except sqlite3.IntegrityError as exc:
            raise DuplicateLabelError(
                f"labeller {labeller_id!r} has already answered pair {pair_id!r}"
            ) from exc

        self._conn.commit()
        return int(cursor.lastrowid)

    # -- reading -----------------------------------------------------------

    def _rows(self, sql: str, params: tuple = ()) -> list[dict]:
        return [dict(row) for row in self._conn.execute(sql, params)]

    def all_labels(self) -> list[dict]:
        return self._rows("SELECT * FROM labels ORDER BY id")

    def labels_for_pair(self, pair_id: str) -> list[dict]:
        return self._rows(
            "SELECT * FROM labels WHERE pair_id = ? ORDER BY id", (pair_id,)
        )

    def labels_by(self, labeller_id: str) -> list[dict]:
        return self._rows(
            "SELECT * FROM labels WHERE labeller_id = ? ORDER BY id", (labeller_id,)
        )

    def labellers(self) -> list[str]:
        """Every labeller who has contributed at least one judgement, sorted."""
        return [
            row["labeller_id"]
            for row in self._conn.execute(
                "SELECT DISTINCT labeller_id FROM labels ORDER BY labeller_id"
            )
        ]

    def count(self) -> int:
        return int(self._conn.execute("SELECT COUNT(*) FROM labels").fetchone()[0])

    # -- backup ------------------------------------------------------------

    def export_csv(self, path: str | Path) -> int:
        """Write every row to CSV. Returns the number of rows written.

        `.gitignore` tells the next reader to keep a CSV export beside the
        database precisely because the database is gitignored and irreplaceable.
        A CSV also survives a corrupted SQLite file and opens in a spreadsheet,
        which matters if the person recovering it is not the person who wrote
        this. The header is written even for an empty store, so a backup taken
        too early is still a valid file rather than a zero-byte puzzle.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        rows = self.all_labels()
        with path.open("w", newline="", encoding="utf-8") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(_COLUMNS))
            writer.writeheader()
            for row in rows:
                writer.writerow(row)
        return len(rows)
