"""`rlhf.store` — the SQLite the human labels land in.

This is the least replaceable artefact in the project: 300 pairs at ~20 seconds
each is ~100 minutes of human time that cannot be regenerated by re-running a
script (PROJECT_BRIEF §6.2, and the note in `.gitignore`). So the tests here are
mostly about refusing to accept data that would quietly corrupt it — a third
choice value, a second opinion from the same person on the same pair — rather
than about the happy path.

Every store in this file is a temporary file, never `results/rlhf/labels.db`.
"""

import sqlite3
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from soc_triage.rlhf.store import (  # noqa: E402
    CHOICES,
    DuplicateLabelError,
    InvalidChoiceError,
    LabelStore,
)


@pytest.fixture
def store(tmp_path):
    with LabelStore(tmp_path / "labels.db") as s:
        yield s


# --------------------------------------------------------------------------
# The happy path, briefly
# --------------------------------------------------------------------------

def test_a_label_survives_a_round_trip(store):
    store.add_label("p0001", "A1", "left", seconds_taken=18.5)
    rows = store.labels_for_pair("p0001")
    assert len(rows) == 1
    assert rows[0]["labeller_id"] == "A1"
    assert rows[0]["choice"] == "left"
    assert rows[0]["seconds_taken"] == 18.5


def test_the_three_choices_are_left_right_and_tie(store):
    """PROJECT_BRIEF §6.2: the labeller clicks left / right / can't tell."""
    assert set(CHOICES) == {"left", "right", "tie"}
    for i, choice in enumerate(CHOICES):
        store.add_label(f"p{i:04d}", "A1", choice)
    assert store.count() == 3


def test_the_database_persists_across_connections(tmp_path):
    """A labelling session is a person closing a laptop, not one process run."""
    path = tmp_path / "labels.db"
    with LabelStore(path) as first:
        first.add_label("p0001", "A1", "right")
    with LabelStore(path) as second:
        assert second.count() == 1
        assert second.labels_for_pair("p0001")[0]["choice"] == "right"


# --------------------------------------------------------------------------
# The two constraints that protect the data
# --------------------------------------------------------------------------

def test_an_unknown_choice_is_rejected(store):
    """'maybe', 'skip', 'Left' — anything outside the three is a bug upstream,
    and the store is the last place it can be caught before it is permanent."""
    for bad in ("maybe", "skip", "Left", "", "LEFT"):
        with pytest.raises(InvalidChoiceError):
            store.add_label("p0001", "A1", bad)
    assert store.count() == 0


def test_one_labeller_cannot_label_the_same_pair_twice(store):
    """This is what makes kappa mean anything.

    Cohen's kappa compares two *independent* opinions. If one person could
    answer the same pair twice, the double-labelled set could silently contain
    one person agreeing with themselves, and kappa would report inter-annotator
    agreement that was never measured.
    """
    store.add_label("p0001", "A1", "left")
    with pytest.raises(DuplicateLabelError):
        store.add_label("p0001", "A1", "right")
    assert store.labels_for_pair("p0001")[0]["choice"] == "left"


def test_two_labellers_may_label_the_same_pair(store):
    """The 50 double-labelled pairs depend on exactly this being allowed."""
    store.add_label("p0001", "A1", "left")
    store.add_label("p0001", "A2", "right")
    assert len(store.labels_for_pair("p0001")) == 2


def test_the_check_constraint_is_in_the_schema_not_only_in_python(store, tmp_path):
    """Defence in depth: Diya's UI writes to this file too, and it will not be
    going through this Python class. The CHECK must hold against raw SQL."""
    raw = sqlite3.connect(tmp_path / "labels.db")
    with pytest.raises(sqlite3.IntegrityError):
        raw.execute(
            "INSERT INTO labels (pair_id, labeller_id, choice, created_at) "
            "VALUES ('p0002', 'A1', 'maybe', '2026-09-04T00:00:00Z')"
        )
    raw.close()


def test_the_unique_constraint_is_in_the_schema_not_only_in_python(store, tmp_path):
    store.add_label("p0001", "A1", "left")
    raw = sqlite3.connect(tmp_path / "labels.db")
    with pytest.raises(sqlite3.IntegrityError):
        raw.execute(
            "INSERT INTO labels (pair_id, labeller_id, choice, created_at) "
            "VALUES ('p0001', 'A1', 'right', '2026-09-04T00:00:00Z')"
        )
    raw.close()


# --------------------------------------------------------------------------
# CONSTRAINTS #23 — labels carry an opaque id, a choice and a timestamp
# --------------------------------------------------------------------------

def test_the_schema_holds_no_field_that_could_identify_a_person(store, tmp_path):
    """CONSTRAINTS #23. If practitioner labels come via Diya's KPMG contacts,
    nothing client- or company-identifying may enter this repository. The
    enforcement is that there is nowhere to put it: the columns are fixed and
    this test fails the moment someone adds `name`, `email` or `employer`.
    """
    raw = sqlite3.connect(tmp_path / "labels.db")
    columns = {row[1] for row in raw.execute("PRAGMA table_info(labels)")}
    raw.close()
    assert columns == {
        "id", "pair_id", "labeller_id", "choice", "created_at", "seconds_taken",
    }


def test_seconds_taken_may_be_null_rather_than_invented(store):
    """A CLI labeller may not measure it. A silently-invented 0.0 would look
    like an instant judgement and would poison any later 'how long did people
    think about this' analysis."""
    store.add_label("p0001", "A1", "tie")
    assert store.labels_for_pair("p0001")[0]["seconds_taken"] is None


def test_created_at_is_written_automatically_in_utc(store):
    store.add_label("p0001", "A1", "left")
    stamp = store.labels_for_pair("p0001")[0]["created_at"]
    assert stamp.endswith("Z"), f"not a UTC ISO-8601 stamp: {stamp}"
    assert stamp[:2] == "20"


def test_created_at_can_be_supplied_for_reproducible_tests(store):
    store.add_label("p0001", "A1", "left", created_at="2026-09-04T12:00:00Z")
    assert store.labels_for_pair("p0001")[0]["created_at"] == "2026-09-04T12:00:00Z"


# --------------------------------------------------------------------------
# Reading it back
# --------------------------------------------------------------------------

def test_labels_by_returns_only_that_labeller(store):
    store.add_label("p0001", "A1", "left")
    store.add_label("p0002", "A1", "right")
    store.add_label("p0001", "A2", "tie")
    assert {r["pair_id"] for r in store.labels_by("A1")} == {"p0001", "p0002"}
    assert {r["pair_id"] for r in store.labels_by("A2")} == {"p0001"}


def test_labellers_lists_who_has_contributed(store):
    store.add_label("p0001", "A1", "left")
    store.add_label("p0001", "A2", "left")
    store.add_label("p0002", "A1", "left")
    assert store.labellers() == ["A1", "A2"]


def test_an_empty_store_reports_zero_rather_than_failing(store):
    assert store.count() == 0
    assert store.labellers() == []
    assert store.labels_for_pair("p0001") == []
    assert store.all_labels() == []


# --------------------------------------------------------------------------
# The backup path the .gitignore comment promises
# --------------------------------------------------------------------------

def test_export_csv_writes_every_row_with_a_header(store, tmp_path):
    """`.gitignore` tells the reader to keep a CSV export beside the database
    because the file is gitignored and irreplaceable. That export has to exist."""
    store.add_label("p0001", "A1", "left", seconds_taken=12.0,
                    created_at="2026-09-04T12:00:00Z")
    store.add_label("p0002", "A2", "tie", created_at="2026-09-04T12:01:00Z")

    out = tmp_path / "labels.csv"
    store.export_csv(out)
    lines = out.read_text(encoding="utf-8").strip().splitlines()

    assert lines[0] == "id,pair_id,labeller_id,choice,created_at,seconds_taken"
    assert len(lines) == 3
    assert lines[1] == "1,p0001,A1,left,2026-09-04T12:00:00Z,12.0"
    assert lines[2] == "2,p0002,A2,tie,2026-09-04T12:01:00Z,"


def test_export_csv_of_an_empty_store_still_writes_the_header(store, tmp_path):
    out = tmp_path / "labels.csv"
    store.export_csv(out)
    assert out.read_text(encoding="utf-8").strip() == (
        "id,pair_id,labeller_id,choice,created_at,seconds_taken"
    )


def test_the_store_creates_its_parent_directory(tmp_path):
    """`results/rlhf/` does not exist on a fresh clone — results/ is gitignored."""
    path = tmp_path / "does" / "not" / "exist" / "labels.db"
    with LabelStore(path) as s:
        s.add_label("p0001", "A1", "left")
    assert path.exists()
